[package]
name = "rrs-lib"
version = "0.1.0"
authors = ["Greg Chadwick <gac@lowrisc.org>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
paste = "1.0"
